name: Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - 'images/**'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          clean: false

      - name: Build and deploy
        run: |
          docker compose --env-file $HOME/web/resume-router/.env up -d --build
          docker image prune -f
